### ISSUE TITLE
Clean up naming schemes

### ISSUE THREAD

**Issue by Lyxal** [Vyxal/Luminespire#1]
Right now, there's tables, lines, sections and cells. And that's a little confusing. I need to think of some better names.

**Comment by Steffan153** [comment]
Sorry, I messed with the code before I saw this. Anyway I cleaned it up.

**Comment by Steffan153** [comment]
I think we should redo it in React or Vue or Svelte or Remix though

**Comment by Lyxal** [comment]
I saw that - thanks! I more mean the variable names and id names. They're a little unorganised right now.

**Comment by Lyxal** [comment]
> I think we should redo it in React or Vue or Svelte or Remix though

Vue if we use a framework

**Comment by Steffan153** [comment]
A framework will make it a lot easier to do the interactivity though. I would actually like to try Svelte but Vue is fine too.

**Comment by Steffan153** [comment]
By the way you could do some simple styling if you want to just add in a build workflow with Tailwind (or use the Play CDN for now), and it'll make it easy to style, and you can add in some quick classes to make it look a little better (if you want)

**Comment by Lyxal** [comment]
> A framework will make it a lot easier to do the interactivity though. I would actually like to try Svelte but Vue is fine too.

Of course - frameworks exist to make doing things easier. I more mean just while I solidify the concept - once I add something rudimentary to generate an explanation, moving to a framework will be fine.

What's the difference between svelte and Vue?

**Comment by Lyxal** [comment]
> By the way you could do some simple styling if you want to just add in a build workflow with Tailwind (or use the Play CDN for now), and it'll make it easy to style, and you can add in some quick classes to make it look a little better (if you want)
> 
> https://tailwindcss.com/docs/installation/play-cdn

I'll look into that when I get the chance.

**Comment by Lyxal** [comment]
> By the way you could do some simple styling if you want to just add in a build workflow with Tailwind (or use the Play CDN for now), and it'll make it easy to style, and you can add in some quick classes to make it look a little better (if you want)
> 
> https://tailwindcss.com/docs/installation/play-cdn

I'll look into that when I get the chance

**Comment by Steffan153** [comment]
https://softwarehut.com/blog/tech/svelte-vs-vue

**Comment by Lyxal** [comment]
> https://softwarehut.com/blog/tech/svelte-vs-vue
> 
> Svelte is a lot faster as far as performance, and it has an interesting syntax and stuff. I've used it a little and it's pretty cool
> 
> But if you like Vue then fine

If svelte is faster we can use that. I only suggested Vue because we've used it before. But that's open to change.

**Comment by Lyxal** [comment]
Apparently sortablejs doesn't have a svelte framework library. It does have a Vue one though.

**Comment by Steffan153** [comment]
That's fine

**Comment by Lyxal** [comment]
Oh cool. We'll use svelte then
